language: node_js
node_js:
- '12.0'
cache: npm
before_install: true
install:
- npm install
before_script: true
script:
- jshint ./src
- "./node_modules/.bin/retire"
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./node_modules/.bin/twly; fi

after_script: true
deploy:
  provider: heroku
  api_key:
    secure: yGeN3HrZcyxdi2vvvXUaOAtRTVfd64ABuRAMdKgUmuJkgGX0U8ShhuV9xa4k63ngRKiNpZIaWCRmFM3Ep30TQhrAd8FG9Vk9F24+jx+4i11VS28TSb7Cf5jH6qS9jh7kDQ89iRO1o0RBDwmY4yHqCyMH1fx7tRB36Yu4q5sh4v3/hKAnm4LJMelJ5/6Nd3+b2ZkZNHhSPlc9WI9G+XoyBub9QiWFQgqvvthikeEUGtKrZ7SG3XJ/9NWQwSUuIZcVUME9M1xr3USfuyjn/8NqUc7gqa2cxMpfrgkaRHjMB7QzgX08bfsVsdx5XclTP97g5TbELQ3nUnB/OdBACsqIzpHpEAS3zjaF+vPiNd4j1/QnToWNfnwxG9ps1AuCImsa6tIfakm/m0eaG8977M4kMXoIX4bFnXzV06KqSXeiCMogW4icXgpJ69Dhi+Myk38jeMLSt0DQL8UEM1ZM5LjV6fPCpA1xqu1SwCtdqvxL53dxdJJgATsqwToe46DTobEloJ0Ra4bKTUcdAP0aGadPHWgzefD9J4/fuUU+YeO8bvmdjoFaMg6uN/06BhFEV+rL4Qfmyq+7Niktj9fch89ZfGmZjxATuXQLHP0pwGH9d4SM6qfjiLW2GGjPCC+0EzMnAbfpnNzEimztHFZuh/XK684iBqQePm8y5zHdGCA+z+E=
  app: ipssi-evaluation-app
  on: dev
